services:
  # Frontend service
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: frontend/build

  # Backend functions service (chỉ chạy một số functions trong backend)
  - type: web
    name: backend-functions
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    plan: free
    branch: main
