services:
  # Frontend service (STATIC SITE)
  - type: static
    name: Frontend
    env: node
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: build  # <--- CHỈ TRỎ TRỰC TIẾP VÀO THƯ MỤC BUILD
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production

  # Backend functions service (SERVERLESS FUNCTIONS)
  - type: functions
    name: Backend-functions
    env: node
    buildCommand: cd Backend && npm install
    plan: free
    branch: main
