services:
  # Frontend (Static Site - React)
  - type: web  # Sửa từ "static" → "web"
    name: my-react-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticDir: frontend/build  # Thêm trường này để chỉ định thư mục tĩnh
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production

  # Backend (Web Service - Node.js/Express)
  - type: web
    name: my-backend-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start  # Ví dụ: "node server.js"
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 10000  # Render tự gán port, nhưng cần khai báo trong code
